/* led.c - pain27 - (C) 2023 a dinosaur */

#include "rgb_anim.h"
#include "led.h"
#include <stdint.h>
#include <avr/io.h>

#define LED_CONCAT(A, B) A ## B
#define SET_LED_HIGH(OUTPORT, PIN) (LED_CONCAT(PORT, OUTPORT) |=  _BV(PIN))
#define SET_LED_LOW(OUTPORT, PIN)  (LED_CONCAT(PORT, OUTPORT) &= ~_BV(PIN))
#define SETUP_LED_OUTPUT(OUTPORT, PIN, STATE) \
	((LED_CONCAT(DDR, OUTPORT) |= _BV(PIN)), SET_LED_##STATE(OUTPORT, PIN))


void hook_early_init(void)
{
	// Setup LED pins as outputs
	SETUP_LED_OUTPUT(TXLED_PORT, TXLED_PIN, HIGH);
	SETUP_LED_OUTPUT(RXLED_PORT, RXLED_PIN, HIGH);
#ifdef BACKLIGHT_ENABLE
	SETUP_LED_OUTPUT(BACKLIGHT_LED_1_PORT, BACKLIGHT_LED_1_PIN, LOW);
	SETUP_LED_OUTPUT(BACKLIGHT_LED_2_PORT, BACKLIGHT_LED_2_PIN, LOW);
	SETUP_LED_OUTPUT(BACKLIGHT_LED_3_PORT, BACKLIGHT_LED_3_PIN, LOW);
#endif
}

void led_set(uint8_t state)
{
	state & _BV(USB_LED_CAPS_LOCK)
		? SET_LED_LOW(RXLED_PORT, RXLED_PIN) : SET_LED_HIGH(RXLED_PORT, RXLED_PIN);
	state & _BV(USB_LED_SCROLL_LOCK)
		? SET_LED_LOW(TXLED_PORT, TXLED_PIN) : SET_LED_HIGH(TXLED_PORT, TXLED_PIN);

#ifdef UNDERGLOW_ENABLE
	rgb_set(0, state & _BV(USB_LED_CAPS_LOCK)
		? (uint8_t[3]){ 0x2F, 0x0F, 0x8 } : (uint8_t[3]){ 0, 0, 0 });
	rgb_set(1, state & _BV(USB_LED_SCROLL_LOCK)
		? (uint8_t[3]){ 0x8, 0x2F, 0 } : (uint8_t[3]){ 0, 0, 0 });
	rgb_update(2);
#endif
}

#ifdef BACKLIGHT_ENABLE

//TODO: PWM
void backlight_set(uint8_t level)
{
	level > 0
		? SET_LED_HIGH(BACKLIGHT_LED_1_PORT, BACKLIGHT_LED_1_PIN)
		: SET_LED_LOW(BACKLIGHT_LED_1_PORT, BACKLIGHT_LED_1_PIN);
	level > 1
		? SET_LED_HIGH(BACKLIGHT_LED_2_PORT, BACKLIGHT_LED_2_PIN)
		: SET_LED_LOW(BACKLIGHT_LED_2_PORT, BACKLIGHT_LED_2_PIN);
	level > 2
		? SET_LED_HIGH(BACKLIGHT_LED_3_PORT, BACKLIGHT_LED_3_PIN)
		: SET_LED_LOW(BACKLIGHT_LED_3_PORT, BACKLIGHT_LED_3_PIN);
}

#endif
